# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: SendEmail@1
  inputs:
        To: 'md.aminul.islam@staht.com'
        From: 'noreply@staht.com'
        Subject: 'APK for Testing'
        Body: 'Hello,Find the attached APK for testing'
        BodyAsHtml: false
        AddAttachment: true
      #  Attachment: 'D:\a\1\s\build\app\outputs\flutter-apk\app-release.apk'
        SmtpServer: 'smtp-mail.outlook.com'
        SmtpUsername: 'noreply@staht.com'
        SmtpPassword: 'Har82283'